### ISSUE TITLE
NoMethodError - undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by mkonecny** [IvanShamatov/sinatra-soap#6]
```
2015-04-10 12:47:01 - NoMethodError - undefined method `+' for nil:NilClass:
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-soap-0.1.7/lib/sinatra/soap/../views/wsdl.builder:15:in `block (5 levels) in singleton class'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-soap-0.1.7/lib/sinatra/soap/../views/wsdl.builder:14:in `each'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-soap-0.1.7/lib/sinatra/soap/../views/wsdl.builder:14:in `block (4 levels) in singleton class'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-soap-0.1.7/lib/sinatra/soap/../views/wsdl.builder:12:in `block (3 levels) in singleton class'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:93:in `method_missing'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-soap-0.1.7/lib/sinatra/soap/../views/wsdl.builder:11:in `block (2 levels) in singleton class'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:93:in `method_missing'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-soap-0.1.7/lib/sinatra/soap/../views/wsdl.builder:2:in `block in singleton class'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-soap-0.1.7/lib/sinatra/soap/../views/wsdl.builder:-2:in `instance_eval'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-soap-0.1.7/lib/sinatra/soap/../views/wsdl.builder:-2:in `singleton class'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-soap-0.1.7/lib/sinatra/soap/../views/wsdl.builder:-4:in `__tilt_14505180'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/tilt-1.4.1/lib/tilt/builder.rb:20:in `evaluate'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:822:in `render'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:791:in `render_ruby'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:701:in `builder'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-soap-0.1.7/lib/sinatra/soap/helper_methods.rb:27:in `get_wsdl'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-soap-0.1.7/lib/sinatra/soap.rb:32:in `block in registered'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/rack-1.6.0/lib/rack/nulllogger.rb:9:in `call'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/rack-parser-0.6.1/lib/rack/parser.rb:23:in `call'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/puma-2.11.1/lib/puma/rack_patch.rb:13:in `call'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in `call'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/puma-2.11.1/lib/puma/configuration.rb:82:in `call'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/puma-2.11.1/lib/puma/server.rb:507:in `handle_request'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/puma-2.11.1/lib/puma/server.rb:375:in `process_client'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/puma-2.11.1/lib/puma/server.rb:262:in `block in run'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/puma-2.11.1/lib/puma/thread_pool.rb:104:in `call'
	/home/martin/workspace/test-server/vendor/bundle/ruby/2.0.0/gems/puma-2.11.1/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
```

Code base:

```
require 'sinatra/soap'

class MyApp < Sinatra::Base
  #remember to register extenstion if you are using modular style
  register Sinatra::Soap 

  set :endpoint  , '/action'
  set :namespace , "http://schemas.xmlsoap.org/wsdl/"
  set :service   , "sinatra"

  soap "GetBalance" do
      params
  end

  soap "DeductBalance" do
      params
  end
end
```

Various Gem Versions:
```
    sinatra (1.4.6)
      rack (~> 1.4)
      rack-protection (~> 1.4)
      tilt (>= 1.3, < 3)

    sinatra-soap (0.1.7)
      nokogiri
      nori (>= 2.0.0)
      sinatra
```

**Comment by mkonecny** [comment]
Seems this was fixed in #4, but is not available in the packaged gem (0.1.7). Could a new gem version be pushed, or should we just fork this repository for now?
